---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-8-4
  name: mysql-8-4-headless
  namespace: mysql-test
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
    - name: mysqlx
      port: 33060
      protocol: TCP
      targetPort: mysqlx
    - name: xcom
      port: 33061
      protocol: TCP
      targetPort: xcom
  selector:
    app: mysql-8-4
  sessionAffinity: None
  type: ClusterIP