---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-mysql
  name: {{ .Release.Name }}-mysql-innodb-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mysql
      port: {{ .Values.innoDbCluster.mysql.port }}
      protocol: TCP
      targetPort: mysql
    - name: mysqlx
      port: 33060
      protocol: TCP
      targetPort: mysqlx
    - name: xcom
      port: 33061
      protocol: TCP
      targetPort: xcom
  selector:
    app: {{ .Release.Name }}-mysql-innodb-cluster
  sessionAffinity: None
  type: ClusterIP