apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  password: {{ .Values.secret.password }}
  admin-password: {{ .Values.secret.adminPassword }}