apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-router-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mysql-router
spec:
  type: {{ .Values.mysqlRouter.service.type }}
  ports:
    - port: {{ .Values.mysqlRouter.router.port }}
      protocol: TCP
      name: router-port
  selector:
    app: {{ .Release.Name }}-mysql-router