apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-8-4-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-8-4-router
  template:
    metadata:
      labels:
        app: mysql-8-4-router
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: mysql-8-4-router-config
            defaultMode: 420
      containers:
        - name: mysql-router
          image: 10.100.54.11:32767/kernel/mysql-community-router:8.4-cps
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mysqlrouter/mysqlrouter.conf
              subPath: mysqlrouter.conf
          env:
            - name: TZ
              value: "UTC+8"
            - name: MYSQL_HOST
              value: "mysql-8-4-0.mysql-8-4-headless.mysql-test.svc.cluster.local"   # 修改成你的 Primary Pod 名稱
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"                     # 建議是有權限進行 bootstrapping 的用戶
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password         # 建議密碼存在 Secret
            - name: MYSQL_CREATE_ROUTER_USER
              value: '0'
            - name: MYSQL_INNODB_CLUSTER_MEMBERS
              value: "3"
            - name: MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS
              value: "--conf-use-sockets --conf-use-gr-notifications"
          ports:
          - name: router-port
            containerPort: 6446   # Default MySQL Router TCP Routing Port
