mysqlVersion: '8.4'

innoDbCluster:
  image: '10.100.54.11:32767/kernel/mysql-community-server:8.4-cps'
  replicaCount: 3
  mysql:
    port: 3306
    user: root
mysqlRouter:
  image: '10.100.54.11:32767/kernel/mysql-community-router:8.4-cps'
  replicaCount: 1
  router:
    port: 6446
  service:
    type: ClusterIP
storage:
  storageClassName: local-storage
  request: 10Gi
secret: #base64
  password: Y3BzMm8yb2Nwcw== # cps2o2ocps
  adminPassword: Y3BzMm8yb2Nwcw==


nodeSelector:
  server-type: mysql
tolerations:
  - key: "server-type"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"

